# Generated by Django 3.2.6 on 2021-11-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentDatabase',
            fields=[
                ('EmiratesID', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('VaccineDoses', models.IntegerField(null=True)),
                ('PCRresults', models.DateField()),
            ],
        ),
    ]
