# Generated by Django 3.2.6 on 2021-11-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('professorID', models.CharField(max_length=500)),
                ('phoneNumber', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomName', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('studentID', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('CurrentExam', models.CharField(max_length=10, null=True)),
                ('CurrentAItimeStamp', models.CharField(max_length=6, null=True)),
                ('CurrentAItextMessage', models.CharField(max_length=500, null=True)),
                ('CurrentAIdangerLevel', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AItimeStamp', models.CharField(max_length=6)),
                ('AItextMessage', models.CharField(max_length=500)),
                ('AIdangerLevel', models.CharField(max_length=500)),
                ('CurrentExam', models.CharField(max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registeration.student')),
            ],
        ),
    ]
