# Generated by Django 3.2.6 on 2021-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professorID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(),
        ),
    ]
