# Generated by Django 3.2.6 on 2021-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professorID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
