# Generated by Django 3.2.6 on 2021-11-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0002_auto_20211105_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='CurrentAIdangerLevel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='CurrentAItextMessage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='CurrentAItimeStamp',
        ),
    ]
