# Generated by Django 3.2.6 on 2021-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0002_auto_20210901_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phoneNumber',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professorID',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=500),
        ),
    ]
