# Generated by Django 3.2.6 on 2021-11-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0003_auto_20211106_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='AItimeStamp',
            field=models.CharField(max_length=30),
        ),
    ]
