# Generated by Django 3.2.6 on 2021-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0003_auto_20210908_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
