# Generated by Django 3.2.6 on 2021-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0004_auto_20210909_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
