# Generated by Django 3.2.6 on 2021-10-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0005_auto_20211021_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
