# Generated by Django 3.2.6 on 2021-10-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0006_auto_20211021_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
