# Generated by Django 3.2.6 on 2021-11-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0007_auto_20211024_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentAIdangerLevel',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentAItextMessage',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentAItimeStamp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentExam',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AItimeStamp', models.CharField(max_length=6)),
                ('AItextMessage', models.CharField(max_length=500)),
                ('AIdangerLevel', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registeration.student')),
            ],
        ),
    ]
