# Generated by Django 3.2.6 on 2021-11-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0009_timeline_currentexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phoneNumber',
        ),
    ]
